### ISSUE TITLE
[BUG] Article empty field

### ISSUE THREAD

**Issue by R3gardless** [SystemConsultantGroup/Git-Study#12]
### Description 📖

작성된 article 에서 작성자와 내용을 안 쓰고 보내면 프론트엔드에서 에러 메시지를 띄워주는 걸로 알고 있는데
누가 악의적으로 강제로 빈 작성자와 내용을 넣어서 보냈어요.
현재 백엔드에서 관련된 로직이 필요할 거 같아요 ㅜ

### Reproduction 🏗️

API Testing Tool을 써서 빈 body 로 넣으니까 문제가 없네요..

<img width="1228" alt="스크린샷 2024-03-28 오후 11 33 32" src="https://github.com/SystemConsultantGroup/Git-Study/assets/48237469/7f09133f-7d43-4b5a-a528-6fdfc27906b5">

빈 Body 로 보내면 400 Bad Request 로 응답하게 고쳐주세요!

### Logs 🪵

```shell
GET /article?content=Welcome 200 2.312 ms - 1991
GET /stylesheets/index.css 304 1.542 ms - -
GET /stylesheets/list.css 304 1.414 ms - -
GET /images/SKKU.jpg 304 0.864 ms - -
GET /javascripts/list.js 304 0.442 ms - -
POST /article/post 200 2.000 ms - 420
```

### Environment 🖥️

MacOS 14.0
Chrome
Thunder Client

### CheckList ✔️

- [x] 관련 Issue 가 이미 존재하는 지 확인해보셨나요?

**Comment by 2tle** [comment]
https://github.com/SystemConsultantGroup/Git-Study/pull/16

말씀해주신 부분 수정 후 PR 올렸습니다.
검토 부탁드립니다!
